services:
  web:
    ports:
      - 5000:80
    image: skyler91/mtgled-svelte:latest
    environment:
      - PYLIGHTS_ADDRESS=pylights:8756
  pylights:
    ports:
      - 8756:8756
    image: skyler91/pylights:latest